import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./components/ClientLayout";
import { SidebarProvider } from "./context/SidebarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  Sidebar,
}: Readonly<{
  children: React.ReactNode;
  Sidebar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex">
            {Sidebar}
            <div className="flex-1">
              <ClientLayout lang="en">{children}</ClientLayout>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
