import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./components/ClientLayout";
import { SidebarProvider } from "./context/SidebarContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextPrisma Server",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  Sidebar,
  modal,
}: Readonly<{
  children: React.ReactNode;
  Sidebar: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900`}>
        <SidebarProvider>
          <div className="flex min-h-screen">
            {Sidebar}
            <div className="flex-1 flex flex-col w-full">
              <ClientLayout lang="en">
                <Suspense fallback={<div className="flex-1 p-4 sm:p-6 lg:p-8">Loading...</div>}>
                  <main className="flex-1 p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto w-full">
                    {children}
                  </main>
                </Suspense>
              </ClientLayout>
              <Suspense fallback={null}>
                {modal}
              </Suspense>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
